### ISSUE TITLE
API guidelines checklist

### ISSUE THREAD

**Issue by davidpdrsn** [davidpdrsn/robin#20]
- [x] Implement error trait for error type https://doc.rust-lang.org/std/error/trait.Error.html
- [x] https://rust-lang-nursery.github.io/api-guidelines/documentation.html#examples-use--not-try-not-unwrap-c-question-mark
- [x] https://rust-lang-nursery.github.io/api-guidelines/documentation.html#cargotoml-includes-all-common-metadata-c-metadata
- [x] https://rust-lang-nursery.github.io/api-guidelines/documentation.html#crate-sets-html_root_url-attribute-c-html-root
- [x] https://rust-lang-nursery.github.io/api-guidelines/documentation.html#release-notes-document-all-significant-changes-c-relnotes
- [x] https://rust-lang-nursery.github.io/api-guidelines/debuggability.html
- [x] https://rust-lang-nursery.github.io/api-guidelines/future-proofing.html#structs-have-private-fields-c-struct-private

Work is happening on the `api-guidelines` branch.
